version: '3.8'

services:
  app:
    container_name: nx-server
    image: wibuswee/nx-server:latest
    command: node index.js
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=mysql
      - DB_USERNAME=${DB_USERNAME}  
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_PORT=3306 
      - JWT_KEY=${JWT_KEY}
    restart: 'on-failure'
    volumes:
      - ./data/nx-space:/root/.nx-space
      - ./data/nx-space/node_modules:/root/.node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    restart: always
    image: mysql
    volumes:
      - ./data/db:/data/db
    environment:
      # 从 env 中获取
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3036:3306"
    networks:
      - app-network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080


networks:
  app-network:
    driver: bridge

