on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  build:
    name: Upload Release Asset
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true
      
      - name: Build bundle
        run: |
          pnpm run bundle
      - name: Test Bundle Server
        run: |
          bash scripts/workflow/test-server.sh
      - name: zip the bundle
        run: |
          zip -r nx-core-bundle.zip out/index.js
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nx-core-bundle.zip
          asset_name: nx-core-bundle-${{ matrix.os }}.zip
          asset_content_type: application/zip

  build_pkg_other_platform:
    name: Build Pkg Platform
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true
      - name: Build project
        run: |
          pnpm run bundle

      - name: Install Pkg
        run: |
          npm install -g pkg
      
      - name: Cache Pkg binaries
        uses: actions/cache@v3
        env:
          cache-name: cache-pkg-binaries
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Build Pkg
        run: |
          pkg .
      - name: Zip Pkg
        run: |
          zip -r nx-core-node16-linux.zip out/core-node16-linux
          zip -r nx-core-node16-macos.zip out/core-node16-macos
          zip -r nx-core-node16-win.zip out/core-node16-win

      - name: Upload macOS Pkg Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.release_url }}
          asset_path: ./nx-core-node16-macos.zip
          asset_name: nx-core-node16-macos.zip.zip
          asset_content_type: application/zip

      - name: Upload Linux Pkg Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.release_url }}
          asset_path: ./nx-core-node16-linux.zip
          asset_name: nx-core-node16-linux.zip.zip
          asset_content_type: application/zip

      - name: Upload Windows Pkg Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.release_url }}
          asset_path: ./nx-core-node16-win.zip
          asset_name: nx-core-node16-win.zip.zip
          asset_content_type: application/zip