name: "upstream"

on:
  schedule:
    - cron: '* * 1/3 * *'
  push:
    branches: [ main ]

jobs:
  upstream:
    name: Upstream
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Upstream
      run: |
        sh ./scripts/upstream.sh
    - name: action-push
      uses: ludeeus/action-push@0.0.1